# Generated by Django 2.1.3 on 2018-11-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Course type',
                'verbose_name_plural': 'Courses type',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=30, verbose_name='Signature')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.CourseType', verbose_name='Course type')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, verbose_name='Name')),
                ('surname', models.CharField(max_length=60, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('github_nick', models.CharField(max_length=100, verbose_name='Github nick')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
